// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/jaredpetersen/vaultx/auth"

	mock "github.com/stretchr/testify/mock"
)

// Method is an autogenerated mock type for the Method type
type Method struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, api
func (_m *Method) Login(ctx context.Context, api auth.API) (auth.Token, error) {
	ret := _m.Called(ctx, api)

	var r0 auth.Token
	if rf, ok := ret.Get(0).(func(context.Context, auth.API) auth.Token); ok {
		r0 = rf(ctx, api)
	} else {
		r0 = ret.Get(0).(auth.Token)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, auth.API) error); ok {
		r1 = rf(ctx, api)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
