name: Build
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: make install
      - name: Build
        run: |
          make generate
          make build
      - name: Validate formatting
        run: test -z $(gofmt -l .)
      - name: Analyze code
        run: make check
      - name: Test
        run: make test
# TODO play with this some more -- ideally we'd build on every branch and then release only on main
# Go-health has this as two workflows
