name: Continuous Integration
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: make install
      - name: Build
        run: |
          make generate
          make build
      - name: Analyze code
        run: make check
      - name: Test
        run: make test