name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: make install
      - name: Build
        run: |
          make generate
          make build
      - name: Validate formatting
        run: test -z $(gofmt -l .)
      - name: Analyze code
        run: make check
      - name: Test
        run: make test
  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Get Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2
#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: v${{ steps.changelog.outputs.version }}
#          name: v${{ steps.changelog.outputs.version }}
#          body: ${{ steps.changelog.outputs.changes }}
#          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
#          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
#          allowUpdates: false
