name: Release
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: make install
      - name: Build
        run: |
          make generate
          make build
      - name: Validate formatting
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Analyze code
        run: make check
      - name: Test
        run: make test
      # TODO set up changelog read and release generation when we're ready to go live
